ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - before: cd playground/1st-proof-of-concept
    init: yarn
    command: yarn start
vscode:
  extensions:
    - PKief.material-icon-theme@3.9.1:g1O+jL+iaYZp5mMmzpPEug==